export const STARTED_ADDING_PHOTO = 'STARTED_ADDING_PHOTO';
export const FINISHED_ADDING_PHOTO = 'FINISHED_ADDING_PHOTO';
export const ERROR_ADDING_PHOTO = 'ERROR_ADDING_PHOTO';
export const STARTED_DELETING_PHOTO = 'STARTED_DELETING_PHOTO';
export const FINISHED_DELETING_PHOTO = 'FINISHED_DELETING_PHOTO';
export const ERROR_DELETING_PHOTO = 'ERROR_DELETING_PHOTO';