export const STARTED_LOADING_PHOTOS = 'STARTED_LOADING_PHOTOS';
export const FINISHED_LOADING_PHOTOS = 'FINISHED_LOADING_PHOTOS';
export const ERROR_LOADING_PHOTOS = 'ERROR_LOADING_PHOTOS';
export const STARTED_UPLOADING_PHOTO = 'STARTED_UPLOADING_PHOTO';
export const FINISHED_UPLOADING_PHOTO = 'FINISHED_UPLOADING_PHOTO';
export const STARTED_SEARCH_PHOTOS='STARTED_SEARCH_PHOTOS';
export const FINISHED_SEARCH_PHOTOS='FINISHED_SEARCH_PHOTOS';
export const ERROR_UPLOADING_PHOTO = 'ERROR_LOADING_PHOTO';